paths:
  base_model_path: "stabilityai/stable-diffusion-xl-base-1.0"
  pretrained_vae_model_name_or_path: "madebyollin/sdxl-vae-fp16-fix"
  lora_weights_path: "BDD_control_lora/runs/lora_sdxl_all_relevant_classes_10k/checkpoint-103500"
  infer_path: "lora_sdxl_generations_scale05_guidance7_train"

prompt: "High resolution, 4k Traffic scene. Train next to the road."
guidance_scale: 7.0
adapter_scale: 0.5
resolution:
  width: 1280
  height: 720
negative_prompt: "cartoon, blurry, low quality, bad anatomy"
num_generations: 60 # generate this many images for a single input mask
num_images_per_prompt: 40 # generate this many images for each input mask